// Curated catalog of footballers a general audience can actually name.
//
// The game only works if the silhouette belongs to someone recognisable, so
// squad-filler pulled from league crawls is deliberately excluded. Names are
// matched against TheSportsDB search, so they use the spelling that service uses.

export const FAMOUS_GOALKEEPERS = [
  'Thibaut Courtois',
  'Alisson',
  'Ederson',
  'Manuel Neuer',
  'Gianluigi Donnarumma',
  'Marc-André ter Stegen',
  'Jan Oblak',
  'David de Gea',
  'Emiliano Martínez',
  'Unai Simón',
  'Mike Maignan',
  'Yassine Bounou',
  'André Onana',
  'Diogo Costa',
  'Gregor Kobel',
  'Wojciech Szczęsny',
  'Keylor Navas',
  'Hugo Lloris',
  'Iker Casillas',
  'Gianluigi Buffon',
  'Petr Čech',
  'Manuel Almunia',
  'Oliver Kahn',
  'Edwin van der Sar',
  'Peter Schmeichel',
  'Dida',
  'Julio Cesar',
  'Victor Valdés',
  'Samir Handanovič',
  'Kasper Schmeichel',
  'Jordan Pickford',
  'Aaron Ramsdale',
  'Alex McCarthy',
];

export const FAMOUS_DEFENDERS = [
  'Virgil van Dijk',
  'Rúben Dias',
  'William Saliba',
  'Josko Gvardiol',
  'Antonio Rüdiger',
  'Éder Militão',
  'David Alaba',
  'Alphonso Davies',
  'Achraf Hakimi',
  'Trent Alexander-Arnold',
  'Andrew Robertson',
  'Kyle Walker',
  'João Cancelo',
  'Reece James',
  'Ben White',
  'Gabriel Magalhães',
  'Cristian Romero',
  'Nicolás Otamendi',
  'Marquinhos',
  'Thiago Silva',
  'Alessandro Bastoni',
  'Federico Dimarco',
  'Theo Hernández',
  'Fikayo Tomori',
  'Matthijs de Ligt',
  'Jules Koundé',
  'Ronald Araújo',
  'Pau Cubarsí',
  'Dani Carvajal',
  'Ferland Mendy',
  'Sergio Ramos',
  'Gerard Piqué',
  'Carles Puyol',
  'Marcelo',
  'Dani Alves',
  'Roberto Carlos',
  'Cafu',
  'Paolo Maldini',
  'Alessandro Nesta',
  'Fabio Cannavaro',
  'Giorgio Chiellini',
  'Leonardo Bonucci',
  'Philipp Lahm',
  'Jérôme Boateng',
  'Ashley Cole',
  'John Terry',
  'Rio Ferdinand',
  'Vincent Kompany',
  'Nemanja Vidić',
  'Kalidou Koulibaly',
  'Aymeric Laporte',
  'Raphaël Varane',
  'Lucas Hernández',
  'Benjamin Pavard',
  'Kieran Trippier',
  'Luke Shaw',
  'Nathan Aké',
];

export const FAMOUS_MIDFIELDERS = [
  'Kevin De Bruyne',
  'Jude Bellingham',
  'Rodri',
  'Luka Modrić',
  'Toni Kroos',
  'Federico Valverde',
  'Aurélien Tchouaméni',
  'Eduardo Camavinga',
  'Pedri',
  'Gavi',
  'Frenkie de Jong',
  'İlkay Gündoğan',
  'Bernardo Silva',
  'Phil Foden',
  'Declan Rice',
  'Martin Ødegaard',
  'Bruno Fernandes',
  'Casemiro',
  'Enzo Fernández',
  'Moisés Caicedo',
  'Cole Palmer',
  'Nicolò Barella',
  'Hakan Çalhanoğlu',
  'Sandro Tonali',
  'Jamal Musiala',
  'Joshua Kimmich',
  'Leon Goretzka',
  'Florian Wirtz',
  'Dani Olmo',
  'Mason Mount',
  'James Maddison',
  'Christian Eriksen',
  'Marco Verratti',
  'Sergej Milinković-Savić',
  'Sergio Busquets',
  'Xavi',
  'Andrés Iniesta',
  'Zinedine Zidane',
  'Andrea Pirlo',
  'Francesco Totti',
  'Steven Gerrard',
  'Frank Lampard',
  'Paul Scholes',
  'Xabi Alonso',
  'Yaya Touré',
  "N'Golo Kanté",
  'Paul Pogba',
  'Mesut Özil',
  'David Silva',
  'Cesc Fàbregas',
  'Arturo Vidal',
  'Clarence Seedorf',
  'Patrick Vieira',
  'Michael Essien',
  'Bastian Schweinsteiger',
  'Kaká',
  'Ronaldinho',
  'Juan Román Riquelme',
  'Michel Platini',
  'Luis Figo',
];

export const FAMOUS_FORWARDS = [
  'Lionel Messi',
  'Cristiano Ronaldo',
  'Kylian Mbappé',
  'Erling Haaland',
  'Neymar',
  'Vinícius Júnior',
  'Rodrygo',
  'Robert Lewandowski',
  'Harry Kane',
  'Mohamed Salah',
  'Bukayo Saka',
  'Son Heung-min',
  'Lautaro Martínez',
  'Victor Osimhen',
  'Rafael Leão',
  'Khvicha Kvaratskhelia',
  'Julián Álvarez',
  'Marcus Rashford',
  'Jack Grealish',
  'Raheem Sterling',
  'Gabriel Jesus',
  'Darwin Núñez',
  'Luis Díaz',
  'Ousmane Dembélé',
  'Antoine Griezmann',
  'Álvaro Morata',
  'Ferran Torres',
  'Lamine Yamal',
  'Nico Williams',
  'Dušan Vlahović',
  'Federico Chiesa',
  'Christopher Nkunku',
  'Serge Gnabry',
  'Leroy Sané',
  'Kingsley Coman',
  'Randal Kolo Muani',
  'Marcus Thuram',
  'Alexander Isak',
  'Ollie Watkins',
  'Dominic Calvert-Lewin',
  'Callum Wilson',
  'Jamie Vardy',
  'Romelu Lukaku',
  'Karim Benzema',
  'Luis Suárez',
  'Edinson Cavani',
  'Sergio Agüero',
  'Zlatan Ibrahimović',
  'Wayne Rooney',
  'Thierry Henry',
  'Didier Drogba',
  'Samuel Eto’o',
  'Ronaldo',
  'Pelé',
  'Diego Maradona',
  'Johan Cruyff',
  'Gerd Müller',
  'Marco van Basten',
  'Ruud van Nistelrooy',
  'Andriy Shevchenko',
  'Alessandro Del Piero',
  'Filippo Inzaghi',
  'Raúl',
  'David Villa',
  'Fernando Torres',
  'Michael Owen',
  'Alan Shearer',
  'Robin van Persie',
  'Arjen Robben',
  'Franck Ribéry',
  'Gareth Bale',
  'Eden Hazard',
  'James Rodríguez',
  'Radamel Falcao',
  'Alexis Sánchez',
  'Sadio Mané',
  'Riyad Mahrez',
  'Pierre-Emerick Aubameyang',
  'Roberto Firmino',
  'Ángel Di María',
  'Gabriel Batistuta',
  'Hernán Crespo',
  'Rivaldo',
  'David Beckham',
  'Ryan Giggs',
  'Paulo Dybala',
  'Memphis Depay',
];

export const FAMOUS_PLAYERS = [
  ...FAMOUS_GOALKEEPERS,
  ...FAMOUS_DEFENDERS,
  ...FAMOUS_MIDFIELDERS,
  ...FAMOUS_FORWARDS,
];

export type CuratedPosition = 'goalkeeper' | 'defender' | 'midfielder' | 'forward';

// TheSportsDB reports a player's *current* role, so retired greats who now
// coach come back as "Manager" and would be dropped. The list they appear in
// is the authority on what they played.
export const CURATED_POSITIONS: Record<string, CuratedPosition> = Object.fromEntries([
  ...FAMOUS_GOALKEEPERS.map((n) => [n, 'goalkeeper' as const]),
  ...FAMOUS_DEFENDERS.map((n) => [n, 'defender' as const]),
  ...FAMOUS_MIDFIELDERS.map((n) => [n, 'midfielder' as const]),
  ...FAMOUS_FORWARDS.map((n) => [n, 'forward' as const]),
]);
