// Retired players are absent from EA's base roster (they only exist as
// Ultimate Team Icons), so their peak rating is curated here on the same
// 0-99 scale. These are our estimates, not EA numbers.
export const LEGEND_PRIME_RATINGS: Record<string, number> = {
  // Goalkeepers
  'Iker Casillas': 90,
  'Gianluigi Buffon': 91,
  'Petr Čech': 89,
  'Oliver Kahn': 90,
  'Edwin van der Sar': 88,
  'Peter Schmeichel': 90,
  Dida: 85,
  'Julio Cesar': 87,
  'Victor Valdés': 86,
  'Keylor Navas': 86,
  'Hugo Lloris': 87,
  'Manuel Almunia': 76,

  // Defenders
  'Paolo Maldini': 93,
  'Alessandro Nesta': 90,
  'Fabio Cannavaro': 90,
  'Carles Puyol': 88,
  'Roberto Carlos': 90,
  Cafu: 89,
  'Sergio Ramos': 90,
  'Gerard Piqué': 87,
  Marcelo: 87,
  'Dani Alves': 88,
  'Giorgio Chiellini': 89,
  'Leonardo Bonucci': 87,
  'Philipp Lahm': 89,
  'Jérôme Boateng': 86,
  'Ashley Cole': 87,
  'John Terry': 87,
  'Rio Ferdinand': 88,
  'Vincent Kompany': 87,
  'Nemanja Vidić': 87,
  'Thiago Silva': 89,
  'Raphaël Varane': 86,
  'David Alaba': 86,

  // Midfielders
  'Zinedine Zidane': 94,
  'Andrea Pirlo': 89,
  'Francesco Totti': 90,
  'Steven Gerrard': 89,
  'Frank Lampard': 88,
  'Paul Scholes': 88,
  'Xabi Alonso': 87,
  'Yaya Touré': 88,
  Xavi: 91,
  'Andrés Iniesta': 91,
  'Sergio Busquets': 87,
  'Clarence Seedorf': 87,
  'Patrick Vieira': 88,
  'Michael Essien': 85,
  'Bastian Schweinsteiger': 88,
  Kaká: 89,
  Ronaldinho: 92,
  'Juan Román Riquelme': 87,
  'Michel Platini': 92,
  'Luis Figo': 91,
  'Mesut Özil': 88,
  'David Silva': 88,
  'Cesc Fàbregas': 87,
  'Arturo Vidal': 86,
  'Marco Verratti': 86,

  // Forwards
  Pelé: 95,
  'Diego Maradona': 95,
  'Johan Cruyff': 93,
  Ronaldo: 94,
  'Thierry Henry': 92,
  'Didier Drogba': 89,
  'Samuel Eto’o': 89,
  'Gerd Müller': 91,
  'Marco van Basten': 92,
  'Ruud van Nistelrooy': 89,
  'Andriy Shevchenko': 90,
  'Alessandro Del Piero': 90,
  'Filippo Inzaghi': 87,
  Raúl: 89,
  'David Villa': 88,
  'Fernando Torres': 87,
  'Michael Owen': 87,
  'Alan Shearer': 89,
  'Robin van Persie': 88,
  'Arjen Robben': 90,
  'Franck Ribéry': 89,
  'Zlatan Ibrahimović': 90,
  'Wayne Rooney': 89,
  'Sergio Agüero': 89,
  'Edinson Cavani': 87,
  'Carlos Tévez': 86,
  Rivaldo: 91,
  'Gabriel Batistuta': 89,
  'Hernán Crespo': 87,
  'David Beckham': 89,
  'Ryan Giggs': 88,
  'Gareth Bale': 89,
  'Eden Hazard': 90,
  'James Rodríguez': 86,
  'Radamel Falcao': 87,
  'Alexis Sánchez': 86,
  'Sadio Mané': 88,
  'Pierre-Emerick Aubameyang': 86,
  'Roberto Firmino': 86,
  'Ángel Di María': 87,
  'Karim Benzema': 90,
  'Luis Suárez': 90,
  'Cristiano Ronaldo': 93,
  'Lionel Messi': 94,
  Neymar: 91,
  'Antoine Griezmann': 89,
  'Riyad Mahrez': 86,
  'Mohamed Salah': 90,
  'Robert Lewandowski': 91,
  'Paulo Dybala': 87,
  'Memphis Depay': 85,
  'Romelu Lukaku': 86,
};
