import { Client } from 'pg';
const c = new Client({ host: `db.${process.env.SUPABASE_PROJECT_REF}.supabase.co`, user: 'postgres', password: process.env.SUPABASE_DB_PASSWORD, database: 'postgres', ssl: { rejectUnauthorized: false } });
await c.connect();
const q = async (s: string) => (await c.query(s)).rows;
const rows = await q(`select gender, position_type, count(*) n from players where ea_id is not null and notable and silhouette_url is not null group by 1,2 order by 1,2`);
for (const r of rows) console.log(`  ${String(r.gender).padEnd(6)} ${r.position_type.padEnd(11)} ${String(r.n).padStart(4)}`);
console.log('subastables :', (await q(`select count(*) from players where ea_id is not null and notable and silhouette_url is not null`))[0].count);
console.log('filas EA    :', (await q(`select count(*) from players where ea_id is not null`))[0].count);
console.log('sin silueta :', (await q(`select count(*) from players where ea_id is not null and not notable`))[0].count);
console.log('con fama    :', (await q(`select count(*) from players where ea_id is not null and fame_score is not null and fame_score > 0`))[0].count);
await c.end();
